---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-yaml
        args: [ --allow-multiple-documents ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: [ --py39-plus ]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args: [ --py39-plus ]
        exclude: ^docs/

  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        args: [
            --line-length=120,
            --target-version=py39
        ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [
            "--ignore=E203,W503,FI10,FI11,FI12,FI13,FI14,FI15,FI16,FI17,FI58,PT013",
          # black
          #     E203 whitespace before ':'
          #     W503 line break before binary operator
          # flake8-future-import
          #     FI10 __future__ import "division" missing
          #     FI11 __future__ import "absolute_import" missing
          #     FI12 __future__ import "with_statement" missing
          #     FI13 __future__ import "print_function" missing
          #     FI14 __future__ import "unicode_literals" missing
          #     FI15 __future__ import "generator_stop" missing
          #     FI16 __future__ import "nested_scopes" missing
          #     FI17 __future__ import "generators" missing
          #     FI58 __future__ import "annotations" present
          # flake8-pytest-style
          #     PT013 found incorrect import of pytest, use simple 'import pytest' instead
            "--max-line-length=120",
          # S101 Use of assert detected
            "--per-file-ignores=docs/*.py:S101",
            "--exclude=*pb2.py,*pb2_grpc.py",
        ]
        exclude: ^docs/

